server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cards?currentSchema=kezlo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
